MaxBlog/accounts/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'accounts'

urlpatterns = [

    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('registration/', views.RegisterCreateView.as_view(), name='registration'),
    path('update/user/<int:pk>/', views.UserUpdateView.as_view(), name='update'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

]

MaxBlog/rest/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from rest_framework.routers import DefaultRouter


from rest.mainpage import views as mainpageViews
from rest.accounts import views as accountsViews

app_name = 'rest'

router = DefaultRouter()
router.register('account/users', accountsViews.UserViewSet)
router.register('post/all', mainpageViews.PostAPIListView)





urlpatterns = [
    #rest for post
    path('v1/post/create', mainpageViews.PostAPICreateView.as_view()),
    path('v1/post/detail/<int:pk>/', mainpageViews.PostAPIDetailView.as_view()),

    #rest authorisation
    path('v1/', include(router.urls)),
    path('v1/auth/', include('djoser.urls.authtoken')),


    ]

MaxBlog/accounts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin

from .managers import UserManager

class User(AbstractBaseUser ,PermissionsMixin):
    email = models.EmailField (_('email address'), unique=True)
    first_name = models.CharField (_('first name'), max_length=25)
    last_name = models.CharField (_('last name'), max_length=25)
    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    avatar = models.ImageField(_('avatar'), upload_to='avatars/', null=True, blank=True, default='static/index.png')
    is_staff = models.BooleanField(_('staff'), default=True)
    is_active = models.BooleanField(_('active'), default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELD = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    @property
    def get_full_name(self):

        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    @property
    def get_short_name(self):

        return self.first_name

MaxBlog/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.contrib.auth.hashers import make_password
from django.utils.translation import ugettext_lazy as _


class LoginForm(AuthenticationForm):
    username = UsernameField(
        max_length = 40,
        widget=forms.TextInput(
            attrs={
                'autofocus': True,
                'class': 'input form-control',
                'placeholder':'Your Email'
            }
        ),
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'class': 'input form-control',
                'placeholder':'Password'
            }
        ),
    )


class CustomUserCreationForm(UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip = False,
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control input'
            }
        ),
    )

    password2 = forms.CharField(
        label=_("Confirm Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        ),
    )

    first_name = forms.CharField(
        label = _("First name"),
        strip=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input'
            }
        ),
    )

    last_name = forms.CharField(
        label = _("Last name"),
        strip=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input'
            }
        ),
    )

    email = forms.CharField(
        label = _("Email"),
        strip=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input'
            }
        ),
    )




    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name')


class CustomUserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        label=_("First name"),
        strip=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input'
            }
        ),
    )

    last_name = forms.CharField(
        label=_("Last name"),
        strip=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input'
            }
        ),
    )

    avatar = forms.ImageField(
        label=_("Image"),
        widget=forms.FileInput(),
        required=False
    )

    class Meta:
        model = get_user_model()
        fields = ("first_name", "last_name", "avatar")

MaxBlog/accounts/views.py
from braces.views import AnonymousRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, UpdateView
from accounts.forms import LoginForm , CustomUserCreationForm , CustomUserUpdateForm
from .models import User



class CustomLoginView(SuccessMessageMixin, AnonymousRequiredMixin, LoginView):
    template_name = 'accounts/login.html'
    success_url = '/'
    form_class = LoginForm
    success_message = _('You are successfully logged in')


class CustomLogoutView(LogoutView):

    next_page = '/'



class RegisterCreateView(AnonymousRequiredMixin, CreateView):
    model = get_user_model()
    form_class = CustomUserCreationForm
    template_name = "accounts/registration.html"



    def __init__(self):
        super().__init__()
        self.avatar = "media/avatarts/index.html"


    def get_success_url(self):
        return reverse_lazy('accounts:login')

    def urlsafe_encode64(bin):
        strict_encode64(bin).tr("+/", "-_").tr('=', '')
        end

    def urlsafe_decode64(str):
        str = str.tr("-_", "+/")
        str = str.ljust((str.length + 3) & ~3, '=')
        strict_decode64(str)
        end

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_active = False
        self.object.save()
        current_site = '0.0.0.0:8080'
        mail_subject = 'Activate your blog account.'
        message = render_to_string('accounts/acc_active_email.html', {
            'user': self.object,
            'domain': current_site,
            'uid': self.object.pk,
            'token': account_activation_token.make_token(self.object),
        })
        to_email = form.cleaned_data.get('email')
        email = EmailMessage(
            mail_subject, message, to=[to_email]
        )
        email.send()
        return HttpResponse('Please confirm your email address to complete the registration')



def activate(request, uidb64, token):
    try:
        uid = uidb64
    except Exception as e:
        user = None
        return HttpResponse(uidb64)

    try:
        user = User.objects.get(pk=uid)
    except Exception as e:
        user = None
        return HttpResponse('user.id')
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account. <a>http://0.0.0.0:8080/login</a>' )
    else:
        return HttpResponse('Activation link is invalid!')



class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'accounts/registration.html'
    success_url = '/'
    form_class = CustomUserUpdateForm
    succes_message = _('Updated')

    def get_queryset(self):
        return self.model.objects.filter(id=self.request.user.id)
    def get_context_data(self, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        context.update({'btn_text': _('Update')})
        return context

MaxBlog/rest/accounts/views.py
from django.contrib.auth import get_user_model
from rest_framework.permissions import IsAdminUser
from rest.accounts.serializers import CreateUserSerializer
from rest_framework import viewsets


User = get_user_model()
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = CreateUserSerializer
    permission_classes = (IsAdminUser, )

MaxBlog/templates/accounts/acc_active_email.html
{% autoescape off %}
Hi {{ user.id }}, {{ domain }} {{ uid }}
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

MaxBlog/templates/accounts/login.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>

    <!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:700%7CNunito:300,600" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="{% static 'js/html5shiv.min.js' %}"></script>
		  <script src="{% static 'js/respond.min.js' %}"></script>
		<![endif]-->
<style>
    .mx-auto{
        margin-left: 30% !important;
        margin-right: 30% !important;
        margin-bottom: auto !important;
        margin-top: 20% !important;
    }
</style>
</head>
<body>
<div class="container">
    <div class="col-md-4 col-md-offset-1 mx-auto">
        <div class="section-row">
            <h3>{% trans 'Log In' %}</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="primary-button" type="submit">{% trans 'Sign In' %}</button>
            </form>
            <br>
            <h4><a href="{% url 'accounts:registration' %}">{% trans "Don't have an account?" %}</h4>
        </div>
    </div>
</div>
</body>
</html>

MaxBlog/templates/accounts/registration.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>

    <!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:700%7CNunito:300,600" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="{% static 'js/html5shiv.min.js' %}"></script>
		  <script src="{% static 'js/respond.min.js' %}"></script>
		<![endif]-->
<style>
    .mx-auto{
        margin-left: 30% !important;
        margin-right: 30% !important;
        margin-bottom: auto !important;
        margin-top: 10% !important;
    }
</style>


</head>
<body>
<div class="container">
    <div class="col-sm-12 col-md-4 col-md-offset-1 mx-auto">
        <div class="section-row">
            {% if user.is_authenticated %}
            <h3>{% trans 'Change Your profile' %}</h3>
            {% else %}
            <h3>{% trans 'Registration' %}</h3>
            {% endif %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="primary-button" type="submit">
                    {% if btn_text %}
                        {{ btn_text }}
                    {% else %}
                        {% trans "Sign up" %}
                    {% endif %}
                </button>
            </form>
            <br>
        </div>
    </div>
</div>
</body>
</html>