MaxBlog/mainpage/urls.py
from django.urls import path
from . import views


app_name = 'mainpage'
urlpatterns = [
    path('', views.PostListView.as_view(), name="list"),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name="detail"),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/post/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path(r'comment_create/<int:post_id>', views.CommentCreateView.as_view(), name='comment_create'),
    path('my_posts', views.MyPostsView.as_view(), name="my_posts"),
    ]

MaxBlog/rest/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from rest_framework.routers import DefaultRouter


from rest.mainpage import views as mainpageViews
from rest.accounts import views as accountsViews

app_name = 'rest'

router = DefaultRouter()
router.register('account/users', accountsViews.UserViewSet)
router.register('post/all', mainpageViews.PostAPIListView)





urlpatterns = [
    #rest for post
    path('v1/post/create', mainpageViews.PostAPICreateView.as_view()),
    path('v1/post/detail/<int:pk>/', mainpageViews.PostAPIDetailView.as_view()),

    #rest authorisation
    path('v1/', include(router.urls)),
    path('v1/auth/', include('djoser.urls.authtoken')),


    ]

MaxBlog/templates/post/includes/comment.html
<!-- comment -->
<div class="media" data-list="comment">
    <div class="media-left">
        <img class="media-object" src="{{ comment.author.avatar.url }}" alt="">
    </div>
    <div class="media-body">
        <div class="media-heading">
            <h4>{{ comment.author }}</h4>
            <span class="time">{{ comment.created_datetime }}</span>
        </div>
        <p>{{ comment.text }}</p>
    </div>
</div>
<!-- /comment -->

MaxBlog/templates/post/includes/comment_form.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}
		{% block header %}
			<div id="post-header" class="page-header">
				<div class="background-img" style="background-image: url('{% static "img/post-page.jpg" %}')"></div>
				<div class="container">
					<div class="row">
						<div class="col-md-10">
							<div class="post-meta">
								<a class="post-category cat-2" href="{{ object.category }}.html">{{ object.category }}</a>
								<span class="post-date">{{ object.created_datetime }}</span>
							</div>
							<h1>{{ object.title }}</h1>
						</div>
					</div>
				</div>
			</div>
		{% endblock %}
		{% block thumb %}
		{% endblock %}
		{% block content %}
						<div class="section-row">
							<div class="section-title">
								<h2>Leave a reply</h2>
							</div>

							<form  class="post-reply" method="post" >
								{% csrf_token %}
								<div class="row">


									<div class="col-md-12">
										<div class="form-group">
											{{ form.as_p }}
										</div>
									<!--<div class="form-group">
											<textarea class="input" name="message" placeholder="Message"></textarea>
										</div> -->
										<button class="primary-button" type="submit" data-action="comment_create" ">Submit</button>
									</div>
								</div>
							</form>
						</div>
						<!-- /reply -->

						<!-- /reply -->

{% endblock %}

MaxBlog/templates/post/includes/content_post.html
{% load i18n %}
{% load category_tags %}

                    <!-- post -->
					<div class="col-md-6">
						<div class="post post">
							<a class="post-img" href="{% url 'mainpage:detail' object.id %}"><img src="{{ object.image.url }}"</a>
							<div class="post-body">
								<div class="post-meta">
									<a class="post-category {% category_attrs object.category %}" href="?filter_category={{ object.category }}">{{ object.category }}</a>
									<span class="post-date">{{ object.created_datetime}}</span>
								</div>
								<h3 class="post-title"><a href="{% url 'mainpage:detail' object.id %}">{{ object.title|truncatechars:40 }}</a></h3>
							</div>
						</div>
					</div>
					<!-- /post -->

MaxBlog/templates/post/includes/favorite.html
        <div class="post post-widget">
            <a class="post-img" href="{% url 'mainpage:detail' object.id %}"><img src="{{ object.image.url }}" alt=""></a>
            <div class="post-body">
                <h3 class="post-title"><a href="{% url 'mainpage:detail' object.id %}">{{ object.title }}</a></h3>
            </div>
        </div>

MaxBlog/templates/post/includes/featered.html
{% load category_tags %}
            <div class="post post-thumb">
                <a class="post-img" href="{% url 'mainpage:detail' object.id %}"><img src="{{ object.image.url }}" alt=""></a>
                <div class="post-body">
                    <div class="post-meta">
                        <a class="post-category {% category_attrs object.category %}" href="{% url 'mainpage:list' %}?filter_category={{ object.category }}">{{ object.category }}</a>
                        <span class="post-date">{{ object.created_datetime }}</span>
                    </div>
                    <h3 class="post-title"><a href="{% url 'mainpage:detail' object.id %}">{{ object.title }}</a></h3>
                </div>
            </div>

MaxBlog/templates/post/includes/newest.html
{% load category_tags %}
            <div class="post post-thumb">
                <a class="post-img" href="{% url 'mainpage:detail' object.id %}"><img src="{{ object.image.url }}" alt=""></a>
                <div class="post-body">
                    <div class="post-meta">
                        <a class="post-category {% category_attrs object.category %}" href="{% url 'mainpage:list' %}?filter_category={{ object.category }}">{{ object.category }}</a>
                        <span class="post-date">{{ object.created_datetime }}</span>
                    </div>
                    <h3 class="post-title"><a href="{% url 'mainpage:detail' object.id %}">{{ object.title }}</a></h3>
                </div>
            </div>

MaxBlog/templates/post/includes/thumb_section.html
{% load i18n %}
{% load category_tags %}
					<!-- post -->
					<div class="col-md-6">
						<div class="post post-thumb">
							<a class="post-img" href="{% url 'mainpage:detail' object.id %}"><img src="{{ object.image.url }}" alt=""></a>
							<div class="post-body">
								<div class="post-meta">
									<a class="post-category {% category_attrs object.category %} " href="?filter_category={{ object.category }}">{{ object.category }}</a>
									<span class="post-date">{{ object.created_datetime }}</span>
								</div>
								<h3 class="post-title"><a href="{% url 'mainpage:detail' object.id %}">{{ object.title|truncatechars:45 }}</a></h3>
							</div>
						</div>
					</div>
					<!-- /post -->