MaxBlog/accounts/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'accounts'

urlpatterns = [

    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('registration/', views.RegisterCreateView.as_view(), name='registration'),
    path('update/user/<int:pk>/', views.UserUpdateView.as_view(), name='update'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

]

MaxBlog/likes/urls.py
from django.urls import path
from .views import *



app_name = 'likes'
urlpatterns = [
    path(r'create/<int:type>/<int:id>', LikeCreateView.as_view(), name='like'),
]

MaxBlog/mainpage/urls.py
from django.urls import path
from . import views


app_name = 'mainpage'
urlpatterns = [
    path('', views.PostListView.as_view(), name="list"),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name="detail"),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/post/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path(r'comment_create/<int:post_id>', views.CommentCreateView.as_view(), name='comment_create'),
    path('my_posts', views.MyPostsView.as_view(), name="my_posts"),
    ]

MaxBlog/rest/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from rest_framework.routers import DefaultRouter


from rest.mainpage import views as mainpageViews
from rest.accounts import views as accountsViews

app_name = 'rest'

router = DefaultRouter()
router.register('account/users', accountsViews.UserViewSet)
router.register('post/all', mainpageViews.PostAPIListView)





urlpatterns = [
    #rest for post
    path('v1/post/create', mainpageViews.PostAPICreateView.as_view()),
    path('v1/post/detail/<int:pk>/', mainpageViews.PostAPIDetailView.as_view()),

    #rest authorisation
    path('v1/', include(router.urls)),
    path('v1/auth/', include('djoser.urls.authtoken')),


    ]

MaxBlog/mainpage/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.utils.translation import ugettext_lazy as _

class PostAbstractModel(models.Model):
    created_datetime = models.DateTimeField(_('Creating time'), auto_now_add=True)
    update_datetime = models.DateTimeField(_('Last changing time'), auto_now_add=True)
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE, verbose_name=_('Author'))

    class Meta:
        abstract = True



class Post(PostAbstractModel):
    CATEGORY_CHOICES =  (
        ('Web Design', 'Web Design'),
        ('JavaScript','JavaScript'),
        ('CSS', 'CSS'),
        ('Jquery', 'Jquery'),
    )
    title = models.CharField(_("Title"), max_length=200)
    second_title = models.CharField(_("Second Title"), max_length=200)
    text = models.TextField(_("News text"))
    category = models.CharField(_("Category"), max_length=100, choices=CATEGORY_CHOICES)
    image = models.ImageField(_("News image"), upload_to='news_images/', null=True, blank=False)
    likes = GenericRelation('likes.Like', related_name='post_likes')

    def __str__(self):
        return " ".join([str(self.created_datetime), self.title])

    class Meta:
        ordering = ('-created_datetime',)
        verbose_name = _("News")
        verbose_name_plural = _("News")



class Comment(PostAbstractModel):
    text = models.TextField(_('Post comment'))
    post = models.ForeignKey('mainpage.Post', on_delete=models.CASCADE, verbose_name=_('comment_post'))

    def __str__(self):
        return "Comment from {0} to post {1}".format(self.author.id, self.post.id)

    class Meta:
        ordering = ('created_datetime',)
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")

MaxBlog/mainpage/forms.py
from .models import Post, Comment
from django import forms
from django.utils.translation import ugettext_lazy as _



class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'second_title', 'text', 'image', 'category']
        widgets = {
            'title': forms.TextInput(),
            'second_title': forms.TextInput(),
            'text': forms.Textarea(),
                    }
        category = forms.MultipleChoiceField(
            widget=forms.CheckboxSelectMultiple,
            choices=Post.CATEGORY_CHOICES
        )

        image = forms.ImageField(
            label=_('Title image'),
            widget=forms.FileInput(
                attrs={
                    'class': 'input'
                },
            ),
            required=False
        )
        #category = forms.ModelChoiceField()


        def __init__(self, *args, **kwargs):
            super(CreatePostForm, self).__init__(*args, **kwargs)
            self.fields['title'].widget.attrs.update({'class': 'input', name: 'title'})
            self.fields['second_title'].widget.attrs.update({'class': 'input', name: 'Second title'})
            self.fields['text'].widget.attrs.update({'class': 'input', name: 'Text'})
            self.fields['category'].widget.attrs.update({'class': 'input', name: 'Category'})



class CreateCommentForm(forms.ModelForm):


    text = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'class': 'input',
                'placeholder': 'Message',
                'name': 'message'
            }
        )
    )

    class Meta:
        model = Comment
        fields = ['text']

MaxBlog/mainpage/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, CreateView, DeleteView, UpdateView, ListView,FormView
from django.utils.translation import ugettext_lazy as _
from django.template.loader import render_to_string
from django_filters.views import FilterView
from .models import Post, Comment
from .forms import CreatePostForm, CreateCommentForm
from .filters import PostFilter
from django.db.models import Count
from .filtermixins import UserPostMixin


def asside_block(context, queryset):
    newest = queryset[:2]
    favorite = queryset.order_by('likes')[0:4]
    css_count = queryset.filter(category='CSS').count()
    js_count = queryset.filter(category='JavaScript').count()
    jq_count = queryset.filter(category='Jquery').count()
    wd_count = queryset.filter(category='Web Design').count()
    context.update({'css_count':css_count,
                    'js_count':js_count,
                    'jq_count':jq_count,
                    'wd_count':wd_count,
                    'favorite': favorite,
                    'newest': newest
                    })
    return context

class PostListView(FilterView):
    filterset_class = PostFilter
    queryset = Post.objects.all()
    template_name = 'post/mainpage.html'
    strict = False
    paginate_by = 10


    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)

        asside_block(context, self.queryset)


        return context

class MyPostsView(PostListView):
    queryset = Post.objects.all()

    def get_queryset(self):
        return self.queryset.filter(author=self.request.user)


class PostDetailView(DetailView):
    template_name = 'post/blog-post.html'
    queryset = Post.objects.all()

    def get_context_data(self, **kwargs):

        #adding CreateCommentForm
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context.update({'form': CreateCommentForm})

        asside_block(context, self.queryset)


        return context

class PostCreateView(CreateView, LoginRequiredMixin):
    form_class = CreatePostForm
    template_name = 'post/form.html'
    queryset = Post.objects.all()

    def get_context_data(self, **kwargs):
        context = super(PostCreateView, self).get_context_data(**kwargs)
        context.update({'btn_text': _('Create')})
        return context

    def form_valid(self, form):
        new_form = form.save(commit=False)
        new_form.author = self.request.user
        new_form.save()
        return HttpResponseRedirect('/')


class PostUpdateView(UpdateView, UserPostMixin):
    form_class = CreatePostForm
    template_name = 'post/form.html'
    queryset = Post.objects.all()
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super(PostUpdateView, self).get_context_data(**kwargs)
        context.update({'btn_text': _('Update')})
        return context
    def get_success_url(self):
        return reverse_lazy('mainpage:detail', kwargs={'pk': self.object.pk})


class PostDeleteView(DeleteView, UserPostMixin):
    template_name = 'post/delete_form.html'
    success_url = '/'
    queryset = Post.objects.all()

class CommentCreateView(CreateView, LoginRequiredMixin):
    model = Comment
    form_class = CreateCommentForm
    template_name = 'post/blog-post.html'
    success_url = '/'


    def form_valid(self, form):
        data_form = form.save(commit=False)
        data_form.author = self.request.user
        data_form.post_id = self.kwargs['post_id']
        data_form.save()
        return JsonResponse({
            'status':'ok',
            'comment': render_to_string('post/includes/comment.html',
                                        context={'comment':data_form})

        })

    def form_invalid(self, form):
        return JsonResponse({'status':'fail', 'form': str(form)})



class CommentDetailView(LoginRequiredMixin, UpdateView):
    template_name = "post/includes/comment.html"
    context_object_name = 'comment'
    fields = '__all__'
    model = Comment

MaxBlog/rest/mainpage/views.py
from rest_framework  import generics
from rest.mainpage.serializers import PostDetailSerializer, PostListSerializer
from mainpage.models import Post
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest.mainpage.permissions import IsOwnerOrReadOnly
from rest_framework.authentication import TokenAuthentication, SessionAuthentication
from rest_framework import viewsets


class PostAPICreateView(generics.CreateAPIView):
    serializer_class = PostDetailSerializer

class PostAPIListView(generics.ListAPIView, viewsets.ModelViewSet):
    serializer_class = PostListSerializer
    queryset = Post.objects.all()
    permission_classes = (IsAdminUser, )


class PostAPIDetailView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = PostDetailSerializer
    queryset = Post.objects.all()
    authentication_classes = (TokenAuthentication, SessionAuthentication)
    permission_classes = (IsOwnerOrReadOnly, )

MaxBlog/templates/post/blog-post.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}
{% load category_tags %}
		{% block header %}
			<div id="post-header" class="page-header">
				<div class="background-img"
					 style="background-image: url('{% static "img/post-page.jpg" %}')">
				</div>
				<div class="container">
					<div class="row">
						<div class="col-md-10">
							<div class="post-meta">
								<a class="post-category {% category_attrs object.category %}" href="?filter_category={{ object.category }}.html">{{ object.category }}</a>
								<span class="post-date">{{ object.created_datetime }}</span>
							</div>
							<h1>{{ object.title }}</h1>
						</div>
					</div>
				</div>
			</div>

		{% endblock %}
		{% block thumb %}
		{% endblock %}

		{% block content %}
		<div class="col-md-10 ">
						<!-- ad -->

						<div class="section-row sticky-container">
							<div class="main-post">
								<div class="section-row text-center">
								<img class="img-responsive" src="{{ object.image.url }}" alt="">
								</div>

								<h3>{{ object.second_title }}</h3>
								<p>{{ object.text }}<br>
                                    {% if user.is_authenticated %}
								<button
									type="button"
									data-action="like"
									data-url="{% url 'likes:like' object.likes.content_type.id object.id %}"
								>
									&hearts;<span id="counter">{% if object.likes.count > 0 %}
									{{ object.likes.count }}{% endif %}</span>
								</button>
    						    {% endif %}

                                </p>

							</div>
                            {% if user == object.author %}
                             <a href="{% url 'mainpage:update' object.id  %}">
                                <button class="primary-button" type="button">
                                        {% trans 'Update' %}
                                </button>
                            </a>
                            <a href="{% url 'mainpage:delete' object.id %}">
                                <button class="primary-button btn-danger " type="button">
                                        {% trans 'Delete' %}
                                </button>
                            </a>
                            {% endif %}



						</div>
                        <div class="section-row text-center">
                            <a href="#" style="display: inline-block;margin: auto;">
                                <img class="img-responsive" src="./img/ad-2.jpg" alt="">
                            </a>
                        </div>




						<!-- author -->
						<div class="section-row">
							<div class="post-author">
								<div class="media">
									<div class="media-left">
										<img class="media-object" src=" {{ object.author.avatar.url }}" alt="">
									</div>
									<div class="media-body">
										<div class="media-heading">
											<h3>{{ object.author.first_name }} {{ object.author.last_name }}</h3>
										</div>
										<p>{% trans 'Date added' %}: {{ object.author.date_added }}</p>

									</div>
								</div>
							</div>
						</div>
						<!-- /author -->

						<!-- comment -->
						<div class="section-row">


							<div class="post-comments">
								{% for comment in object.comment_set.all %}
								{% include 'post/includes/comment.html' %}
								{% endfor %}
							</div>
						</div>
						<!-- /comments -->

						<div class="section-row">
							{% if user.is_authenticated %}
							<div class="section-title">
								<h2>Leave a reply</h2>
							</div>

							<form method="post" action="{% url 'mainpage:comment_create' object.id %}" class="post-reply">
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											{{ form.as_p }}
											{% csrf_token %}
								 			{% if object.comment_set.all %}
												<button  class="primary-button" type="button" data-action="comment_create" >
													{% trans 'Leave a Reply' %}
												</button>
											{% else %}
												<a href="{{ request.get_full.path }}"><button  class="primary-button" type="button" data-action="comment_create" >
													{% trans 'Leave a Reply' %}
												</button></a>
											{% endif %}
										</div>
									</div>
								</div>
							</form>

							{% else %}
							<a href="{% url 'accounts:login' %}"><button  class="primary-button" type="button" >
								{% trans 'Leave a Reply' %}
							</button></a>

							{% endif %}
						</div>
        </div>


		{% endblock %}
{% block extra_js %}
    <script src="{% static 'js/post_detail.js' %}"></script>
    <script>

      $('body').on( 'click', '[data-action="edit_comment"]', function() {
        const url = $( this ).data( 'url' );
        let self = $( this );
        $.get( url, function( e ) {
          self.closest('[data-list="comment"]').replaceWith(e)
        } );
      } );
      $('body').on( 'click', '[data-id="close_edit"]', function() {
        const url = $( this ).data( 'url' );
        let self = $( this );
        $.get( url, function( e ) {
          self.closest('[data-list="comment"]').replaceWith(e)
        } );
      } );
      $('body').on('click', '[data-id="save_comment"]', function () {
        const self = $(this),
                form = self.closest('form');
        let data = {
          'text': form.find('textarea[name="text"]').val(),
          'csrfmiddlewaretoken': form.find('input[name="csrfmiddlewaretoken"]').val()
        };
        $.post(self.data('url'), data, function( e ) {
          if (e.status === 'ok'){
            self.closest('[data-list="comment"]').replaceWith(e.text)
          } else {
            form.replaceWith(e.form)
          }
        })
      })
    </script>
{% endblock %}

MaxBlog/templates/post/delete_form.html
{% extends 'index.html' %}
{% load i18n %}
{% block thumb %}
{% endblock %}
{% block content %}
<div class="col-md-6 col-md-offset-1">
						<div class="section-row">
							<h3>{% trans 'Are you shure, that you want to delete a post?' %}</h3>
							<form method = "post" enctype="multipart/form-data">
								{% csrf_token %}
								<div class="row">
									    <button class="primary-button" type="submit">
												{% trans 'Yes' %}
										</button>
                                    <a href="{% url 'mainpage:list' %}">
										<button class="primary-button" type="button">
												{% trans 'No' %}
										</button>
                                    </a>
                                </div>
							</form>
						</div>
</div>
{% endblock %}

MaxBlog/templates/post/form.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}
{% block thumb %}
{% endblock %}
{% block content %}
<div class="col-md-5 col-md-offset-1">

						<div class="section-row">
							<h3>{% trans 'Create Post' %}</h3>
							<form method = "post" enctype="multipart/form-data">
                            {% csrf_token %}
								<div class="row">
									<div class="col-md-7">
										<div class="form-group">
									{{ form.as_p }}
										<button class="primary-button" type="submit">
											{% if btn_text %}
												{{ btn_text }}
											{% else %}
												{% trans 'Button' %}
											{% endif %}
										</button>
									</div>
								</div>
							</form>
						</div>
					</div>
{% endblock %}
{% block aside %}
{% endblock %}

MaxBlog/templates/post/mainpage.html
{% extends "index.html" %}
{% load i18n %}
{% load pagination %}
    {% block thumb %}

    {% for obj in filter.qs|slice:":2" %}
        {% with obj as object %}
            {% include 'post/includes/thumb_section.html' %}
        {% endwith %}
    {% empty %}
        <h1>{% trans 'Nothing to show' %}</h1>
    {% endfor %}
    {% endblock %}



    {% block content %}
        {% for obj in filter.qs|slice:"2:10" %}
        {% with obj as object %}
            {% include 'post/includes/content_post.html' %}
        {% endwith %}
    {% empty %}
        <h1></h1>
    {% endfor %}
    {% if object_list %}
    <div class="col-md-12"><nav aria-label="...">
          <ul class="pagination">
            {% if page_obj.has_previous %}
            <li >
                <a class="page-link" href="?{% paginating %}1"> {% trans 'First' %}</a>
                <a class="page-link" href="?{% paginating %}{{ page_obj.previous_page_number }}"> {% trans 'Previous' %}</a>
            </li>
            {% endif %}
            <li class="page-item active">
                <span class="current">
                {% trans 'Page' %} {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}.
            </span>
            </li>
           {% if page_obj.has_next %}
            <li >
              <a class="page-link" href="?{% paginating %}{{ page_obj.next_page_number }}">{% trans 'Next' %}&raquo;</a>
              <a class="page-link" href="?{% paginating %}{{ page_obj.paginator.num_pages }}">{% trans 'Last' %}</a>
            </li>
            {% endif %}
          </ul>
        </nav>
    </div>

    {% endif %}

    {% endblock %}
<!-- Pagination -->

        <!-- /Pagination -->